/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    pages: Page;
    media: Media;
    gallery: Gallery;
    forms: Form;
    'form-submissions': FormSubmission;
    users: User;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    'company-info': CompanyInfo;
    header: Header;
    footer: Footer;
  };
}
export interface Page {
  id: string;
  title?: string | null;
  fullTitle?: string | null;
  publishedDate?: string | null;
  slug?: string | null;
  pathname?: string | null;
  hero: HeroField;
  blocks?:
    | (
        | ContentBlock
        | {
            theme?: ('light' | 'dark') | null;
            title?: string | null;
            description?: string | null;
            callToAction?: CallToActionBlock;
            items?:
              | {
                  title?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureChecklist';
          }
        | BannerProps
        | Section
        | GalleryRelationshipProps
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | Media | null;
  };
  parent?: (string | null) | Page;
  breadcrumbs?:
    | {
        doc?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
export interface HeroField {
  type: 'default' | 'primary' | 'minimal' | 'contact';
  containerSize?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  title?: string | null;
  subtitle?: string | null;
  media?: string | Media | null;
  items?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  callToAction?: CallToActionBlock;
  form?: (string | null) | Form;
}
export interface Media {
  id: string;
  alt: string;
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    blur?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
export interface CallToActionBlock {
  text?: string | null;
  disabled?: boolean | null;
  actionType?: ('link' | 'formModal') | null;
  displayType?: ('button' | 'anchor') | null;
  buttonVariant?: ('filled' | 'light' | 'outline' | 'subtle' | 'transparent' | 'white') | null;
  buttonColor?: ('brandPrimary' | 'dark') | null;
  link?: LinkField;
  form?: {
    relationTo: 'forms';
    value: string | Form;
  } | null;
}
export interface LinkField {
  label?: string | null;
  type?: ('internal' | 'external') | null;
  newTab?: boolean | null;
  internal?: {
    relationTo: 'pages';
    value: string | Page;
  } | null;
  external?: string | null;
}
export interface Form {
  id: string;
  title: string;
  type: 'standard' | 'multiStep';
  fields?:
    | (
        | {
            name: string;
            label: string;
            description?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label: string;
            description?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            name: string;
            label: string;
            description?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            orientation?: ('horizontal' | 'vertical') | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'radio';
          }
        | {
            name: string;
            label: string;
            description?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label: string;
            description?: string | null;
            width?: number | null;
            defaultValue?: boolean | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label: string;
            description?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            label?:
              | {
                  [k: string]: unknown;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'privacyPolicy';
          }
      )[]
    | null;
  steps?:
    | {
        fields?:
          | (
              | {
                  name: string;
                  label: string;
                  description?: string | null;
                  width?: number | null;
                  defaultValue?: string | null;
                  required?: boolean | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'text';
                }
              | {
                  name: string;
                  label: string;
                  description?: string | null;
                  width?: number | null;
                  required?: boolean | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'email';
                }
              | {
                  name: string;
                  label: string;
                  description?: string | null;
                  width?: number | null;
                  defaultValue?: string | null;
                  orientation?: ('horizontal' | 'vertical') | null;
                  options?:
                    | {
                        label: string;
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  required?: boolean | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'radio';
                }
              | {
                  name: string;
                  label: string;
                  description?: string | null;
                  width?: number | null;
                  defaultValue?: string | null;
                  options?:
                    | {
                        label: string;
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  required?: boolean | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'select';
                }
              | {
                  name: string;
                  label: string;
                  description?: string | null;
                  width?: number | null;
                  defaultValue?: boolean | null;
                  required?: boolean | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'checkbox';
                }
              | {
                  name: string;
                  label: string;
                  description?: string | null;
                  width?: number | null;
                  defaultValue?: string | null;
                  required?: boolean | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'textarea';
                }
              | {
                  label?:
                    | {
                        [k: string]: unknown;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'privacyPolicy';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  redirect?: LinkField;
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface ContentBlock {
  containerSize?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  theme?: ('light' | 'dark') | null;
  richText?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
export interface BannerProps {
  title?: string | null;
  color?: ('brandPrimary' | 'dark') | null;
  callToAction?: CallToActionBlock;
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
export interface Section {
  sectionTitle?: SectionTitleProps;
  background?: ('white' | 'gray' | 'black') | null;
  blocks?:
    | (FormCardProps | TypeTabsProps | ContentWithImagesProps | StepsProps | AccordionProps | GalleryPreviewBlock)[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'section';
}
export interface SectionTitleProps {
  title?: string | null;
  description?: string | null;
  subtitle?: string | null;
  disabled?: boolean | null;
}
export interface FormCardProps {
  form?: (string | null) | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formCard';
}
export interface TypeTabsProps {
  tabs?:
    | {
        title: string;
        description?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        image?: string | Media | null;
        texture?: string | Media | null;
        list?:
          | {
              title?: string | null;
              description?:
                | {
                    [k: string]: unknown;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  callToAction?: CallToActionBlock;
  id?: string | null;
  blockName?: string | null;
  blockType: 'typeTabs';
}
export interface ContentWithImagesProps {
  richText?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  reversed?: boolean | null;
  images?:
    | {
        image?: string | Media | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contentWithImages';
}
export interface StepsProps {
  items?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
export interface AccordionProps {
  rows?: ('1' | '2') | null;
  variant?: ('default' | 'contained' | 'filled' | 'Separated') | null;
  items?:
    | {
        title?: string | null;
        content?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
export interface GalleryPreviewBlock {
  images?:
    | {
        image?: string | Gallery | null;
        id?: string | null;
      }[]
    | null;
  callToAction?: CallToActionBlock;
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryPreview';
}
export interface Gallery {
  id: string;
  alt: string;
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    blur?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    preview?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    landscape?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    portrait?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
export interface GalleryRelationshipProps {
  displayType: 'mosaic';
  galleryImages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryRelationship';
}
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  photo?: string | Media | null;
  firstName: string;
  lastName: string;
  roles?: ('admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface CompanyInfo {
  id: string;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  address?: string | null;
  yandexMapLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface Header {
  id: string;
  links?:
    | {
        link?: LinkField;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface Footer {
  id: string;
  links?:
    | {
        link?: LinkField;
        id?: string | null;
      }[]
    | null;
  legal?: LinkField;
  legalWarning?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}